/* lang-en.js — Kamus Indonesia → Inggris untuk situs WASKA.
   Simpan dengan nama persis "lang-en.js" dan unggah ke folder yang sama dengan index.html.
   File ini tidak perlu dibuka; cukup diunggah. Teks yang tidak ada di kamus tetap tampil dalam bahasa Indonesia.
   Harga otomatis diubah dari "Rp300.000" menjadi "IDR 300,000". */
window.WASKA_EN=(function(){
const EN={
"Sasirangan Banjar · dibuat tangan pengrajin":"Banjar sasirangan · handmade by artisans",
"Prototipe · ISBPC 2026":"Prototype · ISBPC 2026","Aturan harga":"Pricing rules","Masuk / Daftar":"Log in / Sign up","Keluar":"Log out","Riwayat pesanan":"Order history",
"Produk":"Product","Warna":"Colour","Pratinjau 3D":"3D Preview","Poin & Harga":"Points & Price","Pembayaran":"Payment",
"Pilih produk":"Choose a product",
"Semua produk dibuat hanya setelah dipesan. Harga akhir ditentukan oleh poin kerumitan desain Anda.":"Every product is made only after it is ordered. The final price is set by your design's complexity points.",
"Kain 2 m":"2 m Fabric","Tas Serut":"Drawstring Bag","Lembar kain 2 × 1,15 m":"Fabric piece 2 × 1.15 m","Dompet ritsleting":"Zip pouch","Tas selempang":"Crossbody bag","Tas jinjing":"Handbag","Tas tote / hobo":"Tote / hobo bag",
"Foto contoh produk":"Sample product photo",
"Setiap pesanan termasuk dust bag/kotak, hang tag berisi nama & makna motif, dan kartu terima kasih bertanda tangan pengrajin.":"Every order includes a dust bag or box, a hang tag with the motif names and meanings, and a thank-you card signed by the artisan.",
"Atur foto produk (admin)":"Manage product photos (admin)","Pasang foto produk":"Product photos","Tutup":"Close","Atur foto":"Adjust photo","Pilih foto":"Choose photo","Tambah sudut":"Add angle","Belum ada foto":"No photo yet","Foto dari folder img/":"Photo from folder","utama":"main",
"Foto pertama tiap produk menjadi foto katalog sekaligus dasar pratinjau 3D. Tekan \"Atur foto\" untuk menggeser, memperbesar, mencerahkan, dan memutihkan latar agar semua kartu seragam berlatar putih. Tambahkan foto dari sudut lain (samping, serong, belakang) agar pembeli bisa memutar produk. Setelah selesai, tekan \"Unduh HTML berisi foto\" agar foto dan pengaturannya tersimpan permanen di dalam satu file.":"The first photo of each product is the catalogue photo and the base for the 3D preview. Press \"Adjust photo\" to move, zoom, brighten and whiten the background so all cards look uniform. Add photos from other angles so buyers can rotate the product. When finished, press \"Download HTML with photos\" to save the photos and settings in one file.",
"Selesai":"Done",
"Seret foto untuk menggeser · scroll untuk zoom. Tampilan ini sama persis dengan kartu produk.":"Drag the photo to move it · scroll to zoom. This view matches the product card exactly.",
"Bingkai foto":"Photo frame","Penuhi bingkai":"Fill frame","Tampilkan utuh":"Show whole photo","Perbesar / perkecil":"Zoom in / out","Geser kiri ↔ kanan":"Move left ↔ right","Geser atas ↕ bawah":"Move up ↕ down","Kecerahan":"Brightness","Latar putih otomatis":"Automatic white background","Ganti foto utama":"Replace main photo",
"Nonaktif: latar foto ditampilkan apa adanya.":"Off: the photo background is shown as it is.","✓ Latar sudah diputihkan otomatis.":"✓ Background whitened automatically.","Latar foto tidak terang/polos, jadi foto dibiarkan apa adanya.":"The background is not light or plain, so the photo is left as it is.","Sedang memutihkan latar…":"Whitening the background…",
"Pilih motif":"Choose motifs",
"Pilih dari 14 motif dasar yang disetujui pengrajin Kampung Sasirangan, atau tambahkan motif turunan. Urutan pilihan menentukan susunan lajur motif.":"Choose from 14 base motifs approved by Kampung Sasirangan artisans, or add a derived motif. The order you pick sets the order of the motif stripes.",
"14 motif dasar":"14 base motifs","Pertama 1 poin · tambahan +1":"First 1 point · each extra +1",
"Kewibawaan dan martabat; dahulu dipakai dalam pengobatan":"Authority and dignity; historically used in healing",
"Ketajaman pikiran, dari gigi ikan haruan":"Sharpness of mind, from the teeth of the snakehead fish",
"Persatuan, karena polanya menyambung tanpa putus":"Unity, as the pattern joins without a break",
"Keakraban dan persahabatan, dari bunga kacang panjang":"Closeness and friendship, from the long-bean flower",
"Penolak bala / kemalangan":"Warding off misfortune","Kesuburan":"Fertility",
"Kejujuran: yang di luar sama dengan yang di dalam":"Honesty: what is outside matches what is inside",
"Makna: dikonfirmasi pengrajin":"Meaning: to be confirmed by the artisan",
"Makna dikonfirmasi bersama pengrajin mitra":"Meaning to be confirmed with the partner artisan",
"Motif turunan (bebas)":"Derived motif (free-form)","+2 poin / motif":"+2 points / motif",
"Komposisi bebas dari unsur motif dasar, misalnya lambang sekolah atau komunitas yang digambar ulang bergaya sasirangan. Selalu diperiksa pengrajin.":"A free composition built from base motif elements, such as a school or community emblem redrawn in sasirangan style. Always checked by the artisan.",
"Contoh: Lambang Himpunan Mahasiswa Manajemen":"Example: Management Student Association emblem","Tambah":"Add",
"Logo atau merek pihak ketiga hanya dibuat dengan izin tertulis. Pengrajin berhak menolak desain yang tidak sesuai makna motif.":"Third-party logos or brands are made only with written permission. The artisan may refuse a design that conflicts with a motif's meaning.",
"Cakupan & ukuran motif":"Motif coverage & size","Motif membentuk pita di bagian tertentu":"Motifs form a band on part of the product","Penuh seluruh permukaan":"Full surface","Motif menutupi seluruh bidang":"Motifs cover the whole surface","Motif halus":"Fine motif","Unsur motif di bawah 3 cm atau jarak jelujur rapat":"Motif elements under 3 cm or tight stitch spacing",
"Pilih palet warna":"Choose a colour palette","Palet Anda":"Your palette","Belum ada warna dipilih.":"No colour selected yet.",
"Cari warna… (mis. biru, maroon, sage, pastel, #2E3A78)":"Search colours… (e.g. blue, maroon, sage, pastel, #2E3A78)",
"Merah & merah jambu":"Red & pink","Jingga & kuning":"Orange & yellow","Hijau & tosca":"Green & teal","Biru":"Blue","Ungu":"Purple","Cokelat, netral, hitam & putih":"Brown, neutral, black & white",
"Merah Hati":"Deep Red","Merah Cabai":"Chilli Red","Marun":"Maroon","Merah Bata":"Brick Red","Merah Delima":"Pomegranate Red","Merah Jambu":"Rose Pink","Jingga":"Orange","Terakota":"Terracotta","Salem":"Salmon","Kuning Kunyit":"Turmeric Yellow","Kuning Emas":"Gold","Kuning Jagung":"Corn Yellow",
"Hijau Pucuk":"Shoot Green","Hijau Daun":"Leaf Green","Hijau Pandan":"Pandan Green","Hijau Lumut":"Moss Green","Hijau Botol":"Bottle Green","Hijau Zaitun":"Olive Green","Hijau Sage":"Sage Green","Tosca":"Teal",
"Biru Laut":"Ocean Blue","Biru Malam":"Midnight Blue","Biru Indigo":"Indigo","Biru Benhur":"Royal Blue","Biru Denim":"Denim Blue","Biru Petrol":"Petrol Blue",
"Ungu Terong":"Aubergine","Ungu Anggur":"Grape","Ungu Kecubung":"Amethyst",
"Cokelat Tanah":"Earth Brown","Cokelat Kopi":"Coffee Brown","Cokelat Kayu":"Wood Brown","Cokelat Susu":"Latte","Krem":"Cream","Abu Batu":"Stone Grey","Abu Arang":"Charcoal Grey","Hitam Arang":"Charcoal Black","Putih Gading":"Ivory","Putih Kapas":"Cotton White",
"Merah Muda":"Pink","Biru Langit":"Sky Blue","Kuning Lembut":"Soft Yellow","Salem Muda":"Light Salmon","Sage Muda":"Light Sage","Biru Es":"Ice Blue","Tosca Muda":"Light Teal","Aprikot":"Apricot","Vanila":"Vanilla",
"Warna racikan Anda":"Your custom colours","pastel otomatis +1":"pastel auto +1","Racik warna sendiri":"Mix your own colour","Warna pastel otomatis +1 poin":"Pastel colours automatically +1 point",
"Tidak menemukan warna yang dicari? Pilih bebas dengan pemilih warna atau ketik kode HEX. Warna ini benar-benar dipakai di pratinjau 3D, perhitungan poin, dan dikirim ke pengrajin untuk diracik.":"Can't find the colour you want? Pick any colour with the colour picker or type a HEX code. It is used in the 3D preview and the points calculation, and is sent to the artisan to mix.",
"Kode HEX":"HEX code","Nama warna (opsional)":"Colour name (optional)","mis. Hijau Daun Pisang":"e.g. Banana Leaf Green","Tambah & pakai warna ini":"Add & use this colour",
"Terdekat di katalog:":"Closest in the catalogue:","(hampir sama) ·":"(almost identical) ·","terdeteksi pastel, +1 poin":"detected as pastel, +1 point","· bukan pastel, tanpa poin tambahan":"· not pastel, no extra point","(hampir sama) · bukan pastel, tanpa poin tambahan":"(almost identical) · not pastel, no extra point",
"Kode HEX belum valid. Contoh: #2E7D5B":"Invalid HEX code. Example: #2E7D5B",
"Kode":"Code","belum ada di katalog.":"is not in the catalogue yet.","Pakai warna ini":"Use this colour","Warna “":"The colour “","” belum ada di katalog. Racik sendiri dengan pemilih warna di bawah.":"” is not in the catalogue yet. Mix it yourself with the colour picker below.","Racik warna ini":"Mix this colour",
"Latar gradasi":"Gradient background",
"Warna dasar memudar ke warna kedua (+1 poin, tidak bertambah jika sudah ada pastel)":"The base colour fades into the second colour (+1 point, not added again if a pastel is already used)",
"Warna di layar adalah ilustrasi. Pengrajin mencocokkan dengan swatch kain fisik dan uji celup; toleransi warna dicantumkan dalam ketentuan pesanan.":"On-screen colours are illustrations. The artisan matches them with physical fabric swatches and dye tests; the colour tolerance is stated in the order terms.",
"Pratinjau AI 3D":"AI 3D Preview",
"AI menyusun motif dari 14 motif yang disetujui pengrajin, lalu memasangkannya pada model produk 3D yang bisa Anda putar. Coba gratis, tanpa bayar.":"AI arranges motifs from the 14 artisan-approved motifs and applies them to a product view you can rotate. Free to try, no payment needed.",
"Desain siap dirender":"Design ready to render","Desain berubah":"Design changed",
"Tekan tombol di bawah untuk melihat produk Anda dalam 3D sebelum satu jahitan pun dibuat.":"Press the button below to see your product in 3D before a single stitch is made.",
"Anda mengubah pilihan. Render ulang agar pratinjau 3D sesuai desain terbaru.":"You changed your choices. Re-render so the 3D preview matches the latest design.",
"Buat pratinjau 3D":"Create 3D preview","Render ulang":"Re-render",
"Membaca pustaka 14 motif WASKA…":"Reading the WASKA library of 14 motifs…","Menjelujur & mencelup kain virtual…":"Stitching & dyeing the virtual fabric…","Menjahit bentuk produk 3D…":"Sewing the 3D product shape…","Menata cahaya studio…":"Setting up studio lighting…",
"Pratinjau 3D · ilustrasi, bukan foto produk jadi":"3D preview · an illustration, not a photo of the finished product","Pratinjau 3D · ilustrasi AI, bukan foto":"3D preview · AI illustration, not a photo",
"Seret untuk memutar · scroll / cubit untuk zoom":"Drag to rotate · scroll / pinch to zoom","Geser kiri/kanan untuk memutar":"Swipe left/right to rotate",
"Depan":"Front","Belakang":"Back","Putar":"Spin","Bandingkan foto asli":"Compare with original photo","Lihat desain saya":"View my design",
"Ilustrasi 2D · 3D tidak didukung peramban ini":"2D illustration · 3D is not supported in this browser",
"Variasi lain":"Another variation","Bagikan desain":"Share design","Lihat prompt AI":"Show AI prompt","Sembunyikan prompt AI":"Hide AI prompt",
"Pengrajin memeriksa & memutuskan setiap desain sebelum produksi.":"The artisan checks and decides on every design before production.",
"Foto kain jadi dikirim sebelum dijahit, untuk dicocokkan dengan pratinjau.":"A photo of the finished fabric is sent before sewing, to compare with the preview.",
"Poin kerumitan & harga":"Complexity points & price",
"Harga ditetapkan oleh poin, bukan tawar-menawar. Pengrajin mengonfirmasi level saat memeriksa desain.":"The price is set by points, not bargaining. The artisan confirms the level when checking the design.",
"Rincian poin":"Points breakdown","Motif dasar pertama":"First base motif","Pastel & gradasi":"Pastel & gradient","Warna gradasi":"Gradient colour","Warna pastel":"Pastel colour","Motif penuh seluruh permukaan":"Full-surface motif","Motif halus (< 3 cm / jelujur rapat)":"Fine motif (< 3 cm / tight stitches)",
"Sederhana":"Simple","Menengah":"Medium","Kompleks":"Complex",
"Desain di atas 12 poin: perlu konsultasi pengrajin":"Designs above 12 points need an artisan consultation",
"Sesuai aturan WASKA, desain sangat rumit dikonsultasikan dulu dengan pengrajin sebelum harga diberikan. Anda dapat mengajukan konsultasi di langkah berikutnya, atau mengurangi motif/warna agar harga langsung muncul.":"Under WASKA rules, very complex designs are discussed with the artisan before a price is given. You can request a consultation in the next step, or reduce motifs or colours so the price appears at once.",
"Dibayar":"Paid","lunas":"in full","saat memesan · produksi dimulai setelah desain final disetujui":"when ordering · production starts once the final design is approved","saat memesan":"when ordering",
"Ongkir dibayar terpisah dan tidak termasuk harga.":"Delivery is paid separately and is not included in the price.",
"Bagaimana harga dihitung":"How the price is calculated","Ongkos jahit":"Sewing fee","Kemasan":"Packaging","HPP":"COGS","Dibulatkan ke Rp10.000 terdekat":"Rounded to the nearest Rp10.000",
"Ke mana uang Anda mengalir":"Where your money goes","Pengrajin:":"Artisan:","Penjahit:":"Tailor:","Kemasan:":"Packaging:","Pajak 0,5%:":"Tax 0.5%:",
"Bagian WASKA bukan laba bersih; biaya AI, promosi, situs web, dan honor tim dibayar dari bagian ini.":"WASKA's share is not net profit; AI, promotion, website and team costs are paid from it.",
"Yang Anda terima":"What you receive","Dust bag / kotak kemasan":"Dust bag / gift box","Hang tag berisi nama & makna motif":"Hang tag with motif names & meanings","Kartu terima kasih bertanda tangan pengrajin":"Thank-you card signed by the artisan","Perbaikan gratis jika ada cacat pengerjaan":"Free repair for workmanship defects",
": disusun dari unsur motif dasar, diperiksa pengrajin":": composed from base motif elements, checked by the artisan","[nama pengrajin mitra]":"[partner artisan name]",
"Pesanan dibayar lunas saat memesan. Produksi dimulai setelah pembayaran diterima dan Anda menyetujui desain final dari pengrajin.":"Orders are paid in full when ordering. Production starts after payment is received and you approve the artisan's final design.",
"Memesan sebagai":"Ordering as","Anda belum masuk.":"You are not logged in.","Data pemesan":"Customer details","Nama lengkap":"Full name","Nama":"Name","Pengiriman":"Delivery",
"Antar dalam kota: Banjarmasin":"In-city delivery: Banjarmasin","Antar dalam kota: Banjarbaru":"In-city delivery: Banjarbaru","Kurir (luar kota / luar negeri)":"Courier (other cities / overseas)","Ambil sendiri / jadwal institusi":"Pickup / institution schedule",
"dibayar pembeli, diteruskan penuh ke anggota tim pengantar":"paid by the buyer, passed in full to the delivering team member","sesuai tarif kurir, dibayar pembeli":"at the courier's rate, paid by the buyer","tanpa ongkir":"no delivery fee","Tarif kurir":"Courier rate","tarif kurir":"courier rate","Gratis":"Free",
"Bayar lunas":"Pay in full","Dibayar penuh saat memesan, tanpa pelunasan di akhir":"Paid in full when ordering, with no balance due later","Metode pembayaran":"Payment method","Transfer bank":"Bank transfer",
"Saya memahami bahwa pratinjau AI 3D adalah ilustrasi dengan toleransi warna; pembayaran dikembalikan penuh selama desain final belum saya setujui, tetapi tidak dikembalikan jika saya membatalkan setelah menyetujui desain final.":"I understand that the AI 3D preview is an illustration with a colour tolerance; my payment is fully refunded as long as I have not approved the final design, but is not refunded if I cancel after approving it.",
"Harga produk":"Product price","Ongkir":"Delivery fee","Bayar sekarang":"Pay now",
"Lunas di muka. Tidak ada sisa pembayaran saat produk jadi.":"Paid in full up front. Nothing more to pay when the product is finished.",
"Isi nama, nomor WhatsApp, dan centang persetujuan.":"Fill in your name and WhatsApp number, and tick the agreement.",
"Anda akan diminta masuk/daftar sebelum pembayaran diproses.":"You will be asked to log in or sign up before the payment is processed.",
"Ajukan konsultasi":"Request a consultation","Catatan untuk pengrajin":"Note for the artisan","Kirim permintaan konsultasi":"Send consultation request","Isi nama dan nomor WhatsApp.":"Fill in your name and WhatsApp number.",
"Ringkasan desain":"Design summary","harga langsung":"live price","Belum memilih produk":"No product selected","Poin kerumitan":"Complexity points",
"Poin muncul saat Anda menambah motif & warna.":"Points appear as you add motifs & colours.","Pilih produk untuk melihat harga.":"Choose a product to see the price.","Mulai dari":"From","Di atas 12 poin":"Above 12 points","Konsultasi pengrajin":"Artisan consultation","Konsultasi":"Consultation",
"AI mengusulkan, pengrajin memutuskan, pembeli menyetujui. Tidak ada kain dipotong sebelum pembayaran diterima dan desain final disetujui.":"AI proposes, the artisan decides, the buyer approves. No fabric is cut before payment is received and the final design is approved.",
"Kembali":"Back","Lanjut":"Next","Lanjut ke pembayaran":"Continue to payment",
"Pilih satu produk untuk lanjut.":"Choose a product to continue.","Pilih minimal satu motif.":"Choose at least one motif.","Pilih minimal satu warna.":"Choose at least one colour.","Buat pratinjau 3D dulu.":"Create the 3D preview first.",
"Permintaan konsultasi terkirim":"Consultation request sent","Buat desain baru":"Create a new design",
"Masuk ke akun":"Log in to your account","Gunakan nomor WhatsApp atau email yang terdaftar.":"Use your registered WhatsApp number or email.","No. WhatsApp atau email":"WhatsApp number or email","Lupa password?":"Forgot password?",
"MASUK":"LOG IN","MASUK & LANJUT BAYAR":"LOG IN & CONTINUE TO PAY","MASUK & KIRIM KONSULTASI":"LOG IN & SEND CONSULTATION","ATAU":"OR","Akun demo prototipe":"Prototype demo account","Isi otomatis":"Autofill","Baru di WASKA?":"New to WASKA?","Daftar sekarang":"Sign up now","Masuk":"Log in","Daftar":"Sign up",
"Buat akun baru":"Create a new account","Gratis. Kode verifikasi dikirim lewat WhatsApp.":"Free. A verification code is sent by WhatsApp.","No. WhatsApp (08xxxxxxxxxx)":"WhatsApp number (08xxxxxxxxxx)","Ulangi password":"Repeat password",
"Minimal 8 karakter berisi huruf dan angka.":"At least 8 characters with letters and numbers.","Terlalu lemah":"Too weak","Lemah":"Weak","Cukup":"Fair","Baik":"Good","Kuat":"Strong",
"Saya menyetujui Syarat & Ketentuan serta Kebijakan Privasi WASKA, termasuk dihubungi lewat WhatsApp terkait pesanan.":"I agree to WASKA's Terms & Conditions and Privacy Policy, including being contacted by WhatsApp about my order.",
"DAFTAR":"SIGN UP","Sudah punya akun?":"Already have an account?",
"Ubah data":"Edit details","Verifikasi nomor WhatsApp":"Verify your WhatsApp number","Masukkan 6 digit kode yang kami kirim ke":"Enter the 6-digit code we sent to",
"Prototipe: WhatsApp tidak benar-benar dikirim. Kode demo Anda:":"Prototype: no WhatsApp message is actually sent. Your demo code:",
"VERIFIKASI & BUAT AKUN":"VERIFY & CREATE ACCOUNT","Tidak menerima kode?":"Didn't get the code?","Kirim ulang":"Resend",
"Desainmu, dijelujur tangan pengrajin Banjar.":"Your design, hand-stitched by Banjar artisans.","Simpan desain & lacak pesanan":"Save designs & track orders","Pembayaran kembali penuh sebelum desain final disetujui":"Full refund before the final design is approved","Kabar progres pengrajin lewat WhatsApp":"Artisan progress updates by WhatsApp",
"Prototipe ISBPC 2026 · data akun hanya tersimpan selama sesi ini.":"ISBPC 2026 prototype · account data is kept only for this session.",
"Satu langkah lagi sebelum membayar":"One more step before paying","Satu langkah lagi sebelum konsultasi":"One more step before the consultation","Desain Anda tersimpan dan tidak akan hilang.":"Your design is saved and will not be lost.",
"Masukkan nomor WhatsApp atau email.":"Enter your WhatsApp number or email.","Masukkan password.":"Enter your password.",
"Nomor/email atau password salah. Coba lagi atau daftar akun baru.":"Wrong number/email or password. Try again or create a new account.",
"Nama minimal 3 huruf.":"Name must be at least 3 letters.","Nomor WhatsApp tidak valid (contoh 081234567890).":"Invalid WhatsApp number (example 081234567890).","Nomor ini sudah terdaftar. Silakan masuk.":"This number is already registered. Please log in.",
"Format email tidak valid.":"Invalid email format.","Email ini sudah terdaftar. Silakan masuk.":"This email is already registered. Please log in.","Minimal 8 karakter, berisi huruf dan angka.":"At least 8 characters, with letters and numbers.",
"Konfirmasi password tidak sama.":"Passwords do not match.","Setujui syarat & ketentuan untuk melanjutkan.":"Agree to the terms & conditions to continue.","Kode OTP salah. Periksa kembali 6 digit kode.":"Wrong OTP code. Check the 6 digits again.",
"Lacak pesanan":"Track order","Desain baru":"New design","Pengrajin mitra":"Partner artisan","Pembeli":"Buyer","Tim WASKA (COO)":"WASKA team (COO)","Penjahit mitra":"Partner tailor","Tim WASKA":"WASKA team",
"Apakah desain dapat dijelujur dan sesuai makna motif?":"Can the design be stitched by hand, and does it respect the motif meanings?",
"Pengrajin menyetujui desain tanpa perubahan. Setujui desain final?":"The artisan approved the design without changes. Approve the final design?",
"Kain sedang dijelujur dan dicelup.":"The fabric is being stitched and dyed.","Kain sedang dijelujur dan dicelup (perbaikan).":"The fabric is being stitched and dyed (repair).",
"Periksa kerapian garis motif, ketahanan warna, dan ukuran kain.":"Check the neatness of the motif lines, colour fastness and fabric size.",
"Produk jadi dan sudah lunas. Kemas pesanan.":"The product is finished and fully paid. Pack the order.",
"Setujui tanpa perubahan":"Approve without changes","Usulkan penyesuaian":"Propose an adjustment","Setujui desain final":"Approve final design","Minta revisi":"Request revision",
"Kain selesai → kirim foto & QC":"Fabric finished → send photo & QC","Lolos QC":"Pass QC","Tidak lolos QC":"Fail QC","Tas selesai dijahit":"Bag sewing finished","Kemas & siap kirim":"Pack & ready to ship","Batalkan (pembayaran kembali penuh)":"Cancel (full refund)",
"Ukuran motif halus dinaikkan sedikit (± 3 cm) agar garis jelujur tetap rapi.":"The fine motif size is increased slightly (± 3 cm) so the stitch lines stay neat.",
"Jarak antar-lajur motif diperlebar ± 1 cm agar pewarnaan merata.":"The spacing between motif stripes is widened by ± 1 cm so the dye spreads evenly.",
"Alur pesanan · 6 langkah, 2 keputusan":"Order flow · 6 steps, 2 decisions","Pembeli mendesain":"Buyer designs","Pratinjau AI 3D & harga tetap":"AI 3D preview & fixed price","Pembeli membayar lunas":"Buyer pays in full",
"Pengrajin memeriksa desain":"Artisan checks the design","Boleh menyesuaikan · pembeli menyetujui desain final":"May adjust · buyer approves the final design",
"Pengrajin menerima pembayaran awal 50% & membuat kain":"Artisan receives a 50% advance & makes the fabric",
"Pengrajin dilunasi; penjahit menjahit tas":"Artisan paid in full; tailor sews the bag","Pengrajin dilunasi":"Artisan paid in full","Kain tidak perlu dijahit":"Fabric needs no sewing","Tim mengemas & mengirim":"Team packs & ships","sedang berjalan":"in progress",
"◆ Keputusan: pembeli menyetujui desain final? Tidak → pengrajin & pembeli merevisi":"◆ Decision: does the buyer approve the final design? No → artisan & buyer revise",
"Catatan aktivitas":"Activity log","Arus kas pesanan":"Order cash flow","Uang masuk dari pembeli & pembayaran ke mitra":"Money in from the buyer & payments to partners",
"Pembayaran lunas dari pembeli":"Full payment from buyer","Pembayaran awal 50% ke pengrajin":"50% advance to artisan","Pelunasan 50% ke pengrajin":"Remaining 50% to artisan","Ongkos jahit ke penjahit":"Sewing fee to tailor","Biaya payment gateway 2%":"Payment gateway fee 2%","PPh final 0,5%":"Final income tax 0.5%","Pengembalian pembayaran":"Payment refund",
"Karena pembeli membayar lunas di muka, kas pesanan selalu cukup untuk membayar pengrajin dan penjahit.":"Because the buyer pays in full up front, the order always has enough cash to pay the artisan and tailor.",
"Pesanan dibatalkan sebelum desain final disetujui.":"Order cancelled before the final design was approved.","Pesanan selesai":"Order completed",
"(sama dengan tabel pembagian pendapatan di proposal).":"(the same as the revenue distribution table in the proposal).",
"Kain ini dijelujur dan dicelup dengan tangan khusus untuk Anda. Semoga motifnya membawa makna baik.":"This fabric was stitched and dyed by hand especially for you. May its motifs bring good meaning.",
"Pembeli meminta revisi; desain dikembalikan ke pengrajin.":"The buyer requested a revision; the design goes back to the artisan.",
"Tidak lolos QC (contoh: garis motif kurang rapi). Dikembalikan ke pengrajin untuk diperbaiki tanpa biaya tambahan.":"Failed QC (for example, motif lines not neat). Returned to the artisan for repair at no extra cost.",
"Pesanan dikemas dengan dust bag, hang tag, dan kartu terima kasih.":"The order is packed with a dust bag, hang tag and thank-you card.",
"Diserahkan ke kurir; ongkir sesuai tarif kurir dibayar pembeli.":"Handed to the courier; delivery at the courier's rate is paid by the buyer.",
"Pesanan diambil pembeli / diantar sesuai jadwal institusi.":"Order picked up by the buyer / delivered on the institution's schedule.",
"Lacak pengiriman":"Track shipment","No. resi (simulasi):":"Tracking no. (simulated):","Dikemas":"Packed","Dikirim":"Shipped","Diterima":"Delivered",
"Pesanan sedang disiapkan":"Order is being prepared","Tim WASKA mengemas pesanan dengan dust bag, hang tag, dan kartu terima kasih":"The WASKA team is packing the order with a dust bag, hang tag and thank-you card",
"Paket telah diterima":"Parcel delivered","Pesanan selesai, terima kasih sudah memesan di WASKA":"Order completed, thank you for ordering from WASKA",
"Paket diserahkan ke kurir":"Parcel handed to the courier","Kurir mengambil paket dari WASKA, Banjarmasin":"The courier picked up the parcel from WASKA, Banjarmasin",
"Paket tiba di gudang sortir":"Parcel arrived at the sorting hub","Gudang sortir Banjarmasin":"Banjarmasin sorting hub",
"Paket dalam perjalanan ke kota tujuan":"Parcel in transit to the destination city","Diberangkatkan dari gudang sortir Banjarmasin":"Departed from the Banjarmasin sorting hub",
"Paket dibawa kurir ke alamat Anda":"Parcel out for delivery to your address","Kurir sedang menuju alamat tujuan":"The courier is on the way to the destination address",
"Pesanan siap diambil":"Order ready for pickup","Silakan ambil sesuai jadwal yang disepakati":"Please collect it at the agreed time","Pesanan telah diambil":"Order picked up",
"Paket diambil pengantar":"Parcel collected for delivery","Anggota tim WASKA mengambil paket untuk diantar":"A WASKA team member collected the parcel for delivery","Paket dalam perjalanan ke alamat Anda":"Parcel on the way to your address",
"Menunggu pemeriksaan pengrajin":"Waiting for the artisan's check","Menunggu persetujuan desain":"Waiting for design approval","Sedang dibuat pengrajin":"Being made by the artisan","Pemeriksaan mutu":"Quality check","Sedang dijahit":"Being sewn","Siap dikemas":"Ready to pack","Dalam pengiriman":"In delivery","Dibatalkan":"Cancelled",
"Lihat detail":"View details","Belum ada pesanan":"No orders yet","Pesanan yang sudah Anda bayar akan muncul di sini.":"Orders you have paid for will appear here.","Mulai mendesain":"Start designing",
"Panel CFO":"CFO panel","Aturan poin & daftar harga":"Points rules & price list","Tiap motif dasar tambahan":"Each additional base motif","Tiap motif turunan (bebas)":"Each derived (free-form) motif","Warna sampai 2":"Up to 2 colours","Tiap warna di atas 2":"Each colour beyond 2","Warna pastel atau gradasi":"Pastel or gradient colour",
"Warna racikan sendiri dihitung seperti warna lain; bila terdeteksi pastel otomatis +1. Desain di atas 12 poin → konsultasi pengrajin sebelum harga diberikan. Bobot ditinjau tiap 6 bulan bersama pengrajin.":"Custom colours count like any other colour; if detected as pastel, +1 automatically. Designs above 12 points → artisan consultation before a price is given. Weights are reviewed every 6 months with the artisans.",
"Level & tarif pengrajin":"Levels & artisan rates",
"Harga = (tarif × kain + ongkos jahit + kemasan) × 1,75, dibulatkan ke Rp10.000 terdekat. Pembeli membayar lunas saat memesan.":"Price = (rate × fabric + sewing fee + packaging) × 1.75, rounded to the nearest Rp10.000. The buyer pays in full when ordering.",
"Pengali produk kain 2 m":"Multiplier for the 2 m fabric product","× 1,5 (skenario survei)":"× 1.5 (survey scenario)","Kain":"Fabric",
"Maksimal 6 motif dasar per desain.":"Maximum 6 base motifs per design.","Maksimal 6 warna.":"Maximum 6 colours.","Maksimal 3 motif turunan.":"Maximum 3 derived motifs.",
"Kode HEX tidak valid. Contoh: #2E7D5B":"Invalid HEX code. Example: #2E7D5B","Palet sudah 6 warna.":"The palette already has 6 colours.",
"Warna disimpan, tetapi palet sudah 6 warna. Hapus satu warna dulu.":"Colour saved, but the palette already has 6 colours. Remove one first.","Warna racikan dihapus.":"Custom colour removed.",
"Tautan desain disalin (simulasi). Bagikan ke teman!":"Design link copied (simulated). Share it with friends!",
"Pratinjau 3D tidak tersedia di peramban ini, ditampilkan versi 2D.":"The 3D preview is not available in this browser; showing the 2D version.",
"Simulasi: tautan atur ulang password dikirim ke WhatsApp/email Anda.":"Simulation: a password reset link was sent to your WhatsApp/email.",
"Anda telah keluar dari akun.":"You have logged out.","Foto dihapus.":"Photo removed.","Pengaturan foto dikembalikan ke awal.":"Photo settings reset.",
"index.html berisi pengaturan foto sedang diunduh.":"index.html with the photo settings is downloading.",
"Tampilkan password":"Show password","Sembunyikan password":"Hide password","Hapus warna racikan":"Remove custom colour","Pilih warna":"Pick a colour","Hapus foto":"Remove photo"
};

const has=k=>Object.prototype.hasOwnProperty.call(EN,k);
const T=k=>has(k)?EN[k]:k;
const MON={Januari:"January",Februari:"February",Maret:"March",Mei:"May",Juni:"June",Juli:"July",Agustus:"August",Oktober:"October",Desember:"December",Agu:"Aug",Okt:"Oct",Des:"Dec"};
const DT=x=>x.replace(/\b(Januari|Februari|Maret|Mei|Juni|Juli|Agustus|Oktober|Desember|Agu|Okt|Des)\b/g,w=>MON[w]);
const PT=n=>n+(/^\+?1$/.test(n)?" point":" points");
const NOTE=x=>has(x)?EN[x]:x.replace(/^Motif turunan “(.+)” disederhanakan agar dapat dijelujur dengan tangan\.$/,(a,b)=>"The derived motif “"+b+"” is simplified so it can be stitched by hand.");
const ROLE={Dasar:"Base",Gradasi:"Gradient",Motif:"Motif"};

/* Aturan untuk teks yang berisi angka atau nama; diperiksa berurutan */
const RX=[
[/^Langkah (\d) dari 6$/,m=>"Step "+m[1]+" of 6"],
[/^(\+?\d+(?:–\d+)?\+?) poin$/,m=>PT(m[1])],
[/^Riwayat pesanan \((\d+)\)$/,m=>"Order history ("+m[1]+")"],
[/^Warna pertama menjadi .+ Tersedia (\d+) warna celup, atau racik warna Anda sendiri\.$/,m=>"The first colour is the base dye colour; the next ones are for the motifs. The first two colours are free; each extra colour is +1 point (maximum 6). "+m[1]+" dye colours are available, or mix your own."],
[/^(\d+)\. (Dasar|Gradasi|Motif)$/,m=>m[1]+". "+ROLE[m[2]]],
[/^Pratinjau dibuat sesi ini: (\d+)\. Anggaran AI tahun 1: ±1\.000 gambar\/bulan\.$/,m=>"Previews made this session: "+m[1]+". Year 1 AI budget: about 1,000 images a month."],
[/^Motif dasar tambahan × (\d+)$/,m=>"Additional base motifs × "+m[1]],
[/^Motif turunan × (\d+)$/,m=>"Derived motifs × "+m[1]],
[/^(\d+) warna \(2 pertama gratis\)$/,m=>m[1]+" colours (first 2 free)"],
[/^(\d+) warna \((\d+) di atas 2\)$/,m=>m[1]+" colours ("+m[2]+" beyond 2)"],
[/^(.+) · (Sederhana|Menengah|Kompleks) · (\d+) poin · (Rp[\d.]+) \(lunas\) · dikerjakan (.+) \(antrean terendah\) · akun (.+)$/,m=>T(m[1])+" · "+T(m[2])+" · "+PT(m[3])+" · "+m[4]+" (paid in full) · made by "+m[5]+" (shortest queue) · account "+m[6]],
[/^Harga tetap · (?:level )?(.+)$/,m=>"Fixed price · "+T(m[1])],
[/^Estimasi (\d+)–(\d+) hari \((kain \+ jahit|kain)\)$/,m=>"Estimated "+m[1]+"–"+m[2]+" days ("+(m[3]==="kain"?"fabric":"fabric + sewing")+")"],
[/^(\d+)–(\d+) hari$/,m=>m[1]+"–"+m[2]+" days"],
[/^Pengrajin: (Rp[\d.]+)\/m × (.+)$/,m=>"Artisan: "+m[1]+"/m × "+m[2]],
[/^Pengrajin: (.+)$/,m=>"Artisan: "+T(m[1])],
[/^(.+) · dibuat tangan di Kampung Sasirangan, Banjarmasin$/,m=>T(m[1])+" · handmade in Kampung Sasirangan, Banjarmasin"],
[/^Motif turunan “(.+)”$/,m=>"Derived motif “"+m[1]+"”"],
[/^: (.+)$/,m=>has(m[1])?": "+EN[m[1]]:null],
[/^(.+) · (Sederhana|Menengah|Kompleks)$/,m=>T(m[1])+" · "+T(m[2])],
[/^(.+) · saat kirim$/,m=>T(m[1])+" · on delivery"],
[/^Bayar lunas (Rp[\d.]+)$/,m=>"Pay in full "+m[1]],
[/^Memproses (.+)…$/,m=>"Processing "+T(m[1])+"…"],
[/^Akun diperlukan saat menekan tombol (bayar|kirim konsultasi)\. Desain & isian Anda tetap tersimpan\.$/,m=>"An account is needed when you press the "+(m[1]==="bayar"?"pay":"send consultation")+" button. Your design and details stay saved."],
[/^Desain Anda (\d+) poin \(di atas 12\)\. Pengrajin akan menghubungi Anda untuk membahas kelayakan dan harga\.$/,m=>"Your design scores "+m[1]+" points (above 12). The artisan will contact you to discuss feasibility and price."],
[/^(\d+) poin · (.+)$/,m=>PT(m[1])+" · "+T(m[2])],
[/^Terima kasih, (.+)\. Desain (\d+) poin Anda telah diteruskan ke pengrajin mitra\. Tim WASKA akan menghubungi (.+) lewat WhatsApp untuk membahas kelayakan dan harga\.$/,m=>"Thank you, "+m[1]+". Your "+m[2]+"-point design has been passed to the partner artisan. The WASKA team will contact "+m[3]+" by WhatsApp to discuss feasibility and price."],
[/^Kekuatan password: (.+)$/,m=>"Password strength: "+T(m[1])],
[/^Simulasi alur · giliran: (.+)$/,m=>"Flow simulation · turn: "+T(m[1])],
[/^Pengrajin mengusulkan: (.+) Setujui desain final\?$/,m=>"The artisan proposes: "+NOTE(m[1])+" Approve the final design?"],
[/^Menjahit (.+) beserta lapisan, ritsleting, dan tali\.$/,m=>"Sewing the "+T(m[1])+" with its lining, zip and straps."],
[/^Perbarui status: (.+)$/,m=>"Update status: "+T(m[1])],
[/^(Rp[\d.]+) · jelujur, celup, buka jahitan, lalu QC$/,m=>m[1]+" · stitch, dye, remove stitches, then QC"],
[/^Ongkos jahit (Rp[\d.]+)$/,m=>"Sewing fee "+m[1]],
[/^◆ Keputusan: lolos QC\? Tidak → diperbaiki tanpa biaya(?: \(sudah (\d+)×\))?$/,m=>"◆ Decision: pass QC? No → repaired at no cost"+(m[1]?" ("+m[1]+"× so far)":"")],
[/^Estimasi selesai: (.+)$/,m=>"Estimated completion: "+DT(m[1])],
[/^saldo (.+)$/,m=>"balance "+m[1]],
[/^Pembayaran (Rp[\d.]+) dikembalikan penuh kepada pembeli\. Tidak ada kain yang dipotong atau dicelup\.$/,m=>"The payment of "+m[1]+" is fully refunded to the buyer. No fabric was cut or dyed."],
[/^Hasil akhir pesanan ini: pengrajin (Rp[\d.]+), (?:penjahit (Rp[\d.]+), )?sisa untuk WASKA$/,m=>"Final result of this order: artisan "+m[1]+", "+(m[2]?"tailor "+m[2]+", ":"")+"remainder for WASKA"],
[/^Terima kasih, (.+)!$/,m=>"Thank you, "+m[1]+"!"],
[/^Akun (.+)$/,m=>"Account "+m[1]],
[/^(\d+) pesanan · tersimpan selama sesi prototipe ini$/,m=>m[1]+" orders · kept for this prototype session only"],
[/^(WSK-\d+) · (.+) · (\d+) poin$/,m=>m[1]+" · "+DT(m[2])+" · "+PT(m[3])],
[/^(Sederhana|Menengah|Kompleks) \((.+) poin\)$/,m=>T(m[1])+" ("+m[2]+" points)"],
[/^HPP (Rp[\d.]+)$/,m=>"COGS "+m[1]],
[/^Atur foto katalog: (.+)$/,m=>"Adjust catalogue photo: "+T(m[1])],
[/^(\d+) foto$/,m=>m[1]+" photos"],
[/^Unduh HTML berisi foto \((\d)\/6 produk\)$/,m=>"Download HTML with photos ("+m[1]+"/6 products)"],
[/^(\d)\. (.+)$/,m=>has(m[2])?m[1]+". "+EN[m[2]]:null],
[/^Pesanan dibuat oleh akun (.+)\. Pembayaran lunas (Rp[\d.]+) diterima via (.+)\.$/,m=>"Order created by account "+m[1]+". Full payment of "+m[2]+" received via "+T(m[3])+"."],
[/^Desain dikirim ke (.+) untuk diperiksa \(antrean minggu ini: (\d)\/5\)\.$/,m=>"Design sent to "+m[1]+" for checking (queue this week: "+m[2]+"/5)."],
[/^(.+) memeriksa desain: dapat dibuat, makna motif sesuai\. Level dikonfirmasi: (.+) \((\d+) poin\)\.$/,m=>m[1]+" checked the design: it can be made and the motif meanings are respected. Level confirmed: "+T(m[2])+" ("+PT(m[3])+")."],
[/^(.+) mengusulkan penyesuaian: (.+) Level tetap (.+)\.$/,m=>m[1]+" proposes an adjustment: "+NOTE(m[2])+" The level stays "+T(m[3])+"."],
[/^Pembeli menyetujui desain final\. Pembayaran awal 50% diteruskan ke (.+); produksi dimulai\. Sejak saat ini pembayaran tidak dapat dikembalikan bila batal\.$/,m=>"The buyer approved the final design. A 50% advance is passed to "+m[1]+"; production starts. From now on the payment cannot be refunded if the order is cancelled."],
[/^Kain selesai\. Foto kain jadi dikirim ke pembeli( sebelum dijahit)?\.$/,m=>"Fabric finished. A photo of the finished fabric is sent to the buyer"+(m[1]?" before sewing":"")+"."],
[/^Lolos QC\. Pengrajin dilunasi (Rp[\d.]+)\.( Kain diteruskan ke penjahit mitra\.)?$/,m=>"Passed QC. The artisan is paid the remaining "+m[1]+"."+(m[2]?" The fabric goes to the partner tailor.":"")],
[/^(.+) selesai dijahit\. Penjahit dibayar (Rp[\d.]+)\.$/,m=>T(m[1])+" sewing finished. The tailor is paid "+m[2]+"."],
[/^Diantar anggota tim; ongkir (Rp[\d.]+) diteruskan penuh ke pengantar\.$/,m=>"Delivered by a team member; the "+m[1]+" delivery fee is passed in full to them."],
[/^Pembeli membatalkan sebelum menyetujui desain final\. Pembayaran (Rp[\d.]+) dikembalikan penuh\.$/,m=>"The buyer cancelled before approving the final design. The payment of "+m[1]+" is fully refunded."],
[/^“(.+)” ditambahkan ke palet( \(pastel \+1 poin\))?\.$/,m=>"“"+T(m[1])+"” added to the palette"+(m[2]?" (pastel +1 point)":"")+"."],
[/^“(.+)” sudah ada di palet Anda\.$/,m=>"“"+T(m[1])+"” is already in your palette."],
[/^Kode OTP \(simulasi\) dikirim ke WhatsApp: (\d+)$/,m=>"OTP code (simulated) sent by WhatsApp: "+m[1]],
[/^Kode OTP baru \(simulasi\): (\d+)$/,m=>"New OTP code (simulated): "+m[1]],
[/^Akun dibuat\. Selamat datang, (.+)!$/,m=>"Account created. Welcome, "+m[1]+"!"],
[/^Selamat datang kembali, (.+)!$/,m=>"Welcome back, "+m[1]+"!"],
[/^(.+?)\. (.+)\.$/,m=>has(m[1])&&has(m[2])?EN[m[1]]+". "+EN[m[2]]+".":null]
];

/* Harga: "Rp300.000" → "IDR 300,000" (kode mata uang internasional, pemisah ribuan koma) */
const IDR=s=>s.replace(/Rp(\d{1,3}(?:\.\d{3})*)/g,(a,n)=>"IDR "+n.replace(/\./g,","));
function lookup(k){
  if(has(k))return EN[k];
  for(let i=0;i<RX.length;i++){
    const m=k.match(RX[i][0]);
    if(m){const o=RX[i][1](m);if(o!=null)return o;}
  }
  return null;
}
/* Mengembalikan terjemahan, atau null bila tidak ada yang perlu diubah */
return function(k){
  const v=lookup(k),out=IDR(v==null?k:v);
  return out===k?null:out;
};
})();
